apiVersion: 1

datasources:
  - name: Prometheus
    uid: bfx714adccgsga
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Loki
    uid: ffx74s2v4uq68a
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true

  - name: InfluxDB-NetFlow
    uid: influxdb-netflow
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: netmon
      defaultBucket: netflow
      tlsSkipVerify: true
    secureJsonData:
      token: netmon-local-dev-token-2026
    editable: true
